### ISSUE TITLE
1.1.5?

### ISSUE THREAD

**Issue by jinjor** [lovasoa/elm-csv#6]
It seems `README.md` has been updated in the last commit but the latest version(1.1.5) is not out yet. Do you mind publishing it soon?

Also, this fork repository links to the original package doc. Is this possible to change it to http://package.elm-lang.org/packages/lovasoa/elm-csv/latest ?

**Comment by lovasoa** [comment]
Answering 3 years later... The latest version has been published https://package.elm-lang.org/packages/lovasoa/elm-csv/latest/Csv
